export const KAPAKLI_MAHALLELERI = [
  "Atatürk",
  "Bahçelievler",
  "Cumhuriyet",
  "İnönü",
  "İsmetpaşa",
  "Bahçeağıl",
  "Karlı",
  "Pınarca",
  "Uzunhacı",
  "Yanıkağıl",
  "Fatih",
  "Karaağaç",
  "Kazımkarabekir",
  "Mimar Sinan",
  "Adnan Menderes",
  "Mevlana",
  "Ömer Halisdemir",
  "Vatan",
  "Yıldızkent",
  "Yunus Emre",
  "19 Mayıs",
];
