// NOT: Bu metinler taslak niteligindedir; yayina alinmadan once hukuk
// birimi tarafindan incelenip onaylanmalidir.

export const KVKK_METNI = `Kapaklı Belediyesi ("Belediye") olarak, 6698 sayılı Kişisel Verilerin Korunması Kanunu ("KVKK") kapsamında veri sorumlusu sıfatıyla, bu mobil uygulama üzerinden elde ettiğimiz kişisel verilerinizin işlenmesine ilişkin sizleri bilgilendirmek isteriz. Uygulama üzerinden ad, soyad, T.C. kimlik numarası, telefon numarası, e-posta adresi, konum bilgisi, ikamet ettiğiniz mahalle/adres ve varsa profil fotoğrafınız gibi kişisel verileriniz; hesabınızı oluşturmanız, talep ve başvurularınızı iletmeniz ya da belediye hizmetlerinden faydalanmanız sırasında tarafımızca işlenmektedir.

Kişisel verileriniz; belediye hizmetlerinin sunulması ve geliştirilmesi, talep ve başvurularınızın alınması, değerlendirilmesi ve sonuçlandırılması, size yönelik bilgilendirme ve bildirim gönderilmesi, hizmet kalitesinin ölçülmesi ile yasal yükümlülüklerimizin yerine getirilmesi amaçlarıyla, KVKK'nın 5. ve 6. maddelerinde belirtilen "veri sorumlusunun hukuki yükümlülüğünü yerine getirebilmesi için zorunlu olması", "bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması" ve "ilgili kişinin temel hak ve özgürlüklerine zarar vermemek kaydıyla veri sorumlusunun meşru menfaati için zorunlu olması" hukuki sebeplerine dayanılarak işlenmektedir. Verileriniz, ilgili mevzuatın izin verdiği ölçüde ve gerektiğinde yetkili kamu kurum ve kuruluşlarıyla, hizmetin ifası için çalıştığımız tedarikçi ve iş ortaklarımızla paylaşılabilir; bu paylaşımlar dışında üçüncü kişilerle ticari amaçla paylaşılmaz.

KVKK'nın 11. maddesi uyarınca; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi talep etme, işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında verilerin aktarıldığı üçüncü kişileri bilme, eksik veya yanlış işlenmişse düzeltilmesini isteme, KVKK'da öngörülen şartlar çerçevesinde silinmesini veya yok edilmesini isteme, yapılan işlemlerin verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, işlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhinize bir sonucun ortaya çıkmasına itiraz etme ve kanuna aykırı işleme sebebiyle zarara uğramanız hâlinde zararın giderilmesini talep etme haklarına sahipsiniz. Bu haklarınızı kullanmak için Belediyemize yazılı olarak veya Kişisel Verileri Koruma Kurulu'nun belirlediği diğer yöntemlerle başvurabilirsiniz.

Kişisel verileriniz, işlenme amacının gerektirdiği süre boyunca ve ilgili mevzuatta öngörülen zamanaşımı süreleri saklı kalmak kaydıyla saklanmakta; bu sürelerin sonunda silinmekte, yok edilmekte veya anonim hâle getirilmektedir. Belediyemiz, kişisel verilerinizin hukuka aykırı olarak işlenmesini ve erişilmesini önlemek, muhafazasını sağlamak amacıyla uygun güvenlik düzeyini temin etmeye yönelik gerekli her türlü teknik ve idari tedbiri almayı taahhüt eder.`;

export const KULLANIM_SARTLARI_METNI = `Bu mobil uygulama, Kapaklı Belediyesi ("Belediye") tarafından vatandaşlarımıza belediye hizmetlerine daha hızlı ve kolay erişim sağlamak; duyuru, güncel içerik, talep/başvuru takibi ve bildirim gibi işlevleri tek bir platform üzerinden sunmak amacıyla geliştirilmiştir. Uygulamayı kullanarak aşağıda yer alan kullanım şartlarını kabul etmiş sayılırsınız.

Uygulamaya kayıt olurken ve kullanım süresince paylaştığınız bilgilerin (ad, soyad, T.C. kimlik numarası, telefon, e-posta ve benzeri) doğru, güncel ve size ait olması sizin sorumluluğunuzdadır. Hesap bilgilerinizin ve şifrenizin gizliliğini korumak, hesabınız üzerinden gerçekleştirilen tüm işlemlerden sorumlu olmak sizin yükümlülüğünüzdedır. Hesabınızla ilgili yetkisiz bir kullanım fark etmeniz hâlinde durumu vakit kaybetmeden Belediyemize bildirmeniz gerekmektedir.

Uygulama üzerinden sunulan talep/başvuru oluşturma, duyuru ve güncel içerikleri görüntüleme, harita ve konum tabanlı hizmetlerden faydalanma gibi işlevler, yalnızca gerçek ve doğru bilgilerle, iyi niyet çerçevesinde ve belediye hizmetlerinin amacına uygun şekilde kullanılabilir. Uygulamanın kötüye kullanılması, yanıltıcı bilgi girilmesi veya başkalarının haklarını ihlal edecek şekilde kullanılması durumunda Belediyemiz ilgili hesabı askıya alma veya kapatma hakkını saklı tutar.

Belediyemiz, uygulamanın kesintisiz ve hatasız çalışacağını garanti etmez; bakım, güncelleme veya teknik nedenlerle hizmetlerde geçici aksaklıklar yaşanabilir. Belediyemiz, üçüncü taraf hizmetler (harita, bildirim, ödeme gibi) üzerinden kaynaklanabilecek aksaklıklardan sorumlu tutulamaz. İşbu kullanım şartları, hizmetlerin geliştirilmesi veya mevzuatta yapılacak değişiklikler doğrultusunda zaman zaman güncellenebilir; güncel şartlar uygulama üzerinden yayımlandığı andan itibaren geçerli olur.`;
